server:
  port: 0

spring:
  application:
    name: main-service

  mvc:
    format:
      date: yyyy-MM-dd
      date-time: yyyy-MM-dd HH:mm:ss
      time: HH:mm:ss
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Europe/Moscow
    locale: ru_RU

  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5434/main-db}
    username: ${SPRING_DATASOURCE_USERNAME:admin}
    password: ${SPRING_DATASOURCE_PASSWORD:100}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    org:
      zalando:
        logbook: DEBUG
    ru.practicum.ewm.client: DEBUG
